# Generated by Django 3.2.5 on 2022-04-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area_38_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='reportName',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
